name: Build and deploy
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Print context
        run: echo "@{{toJSON(github)}}"
      - name: Install dependencies
        run: npm install
      - name: Remove old builds
        run: rm -rf build.zip build || true
      - name: Build project
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: build
          name: build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get build project
        uses: actions/download-artifact@v4
        with:
          name: build